import type { Config } from "tailwindcss";

export default {
	important: true,
	content: ["./src/**/*"],
	theme: {
		fontFamily: {
			"serif": ["var(--font-serif)", "var(--font-emoji)"],
			"sans": ["var(--font-sans)", "var(--font-emoji)"],
			"geometric": ["var(--font-geometric)", "var(--font-sans)", "var(--font-emoji)"],
			"sung": ["var(--font-sung)", "var(--font-serif)", "var(--font-emoji)"],
			"hei": ["var(--font-hei)", "var(--font-sans)", "var(--font-emoji)"],
			"kai-fallback-sung": ["var(--font-kai)", "var(--font-sung)", "var(--font-serif)", "var(--font-emoji)"],
			"kai-fallback-hei": ["var(--font-kai)", "var(--font-hei)", "var(--font-sans)", "var(--font-emoji)"],
			"devanagari": ["var(--font-devanagari)", "var(--font-sans)", "var(--font-emoji)"],
			"arabic": ["var(--font-arabic)", "var(--font-sans)", "var(--font-emoji)"],
			"chinese-chocolate-classical-sans": ['"Chocolate Classical Sans"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-huninn": ['"Huninn"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-bpmf-huninn": ['"Bpmf Huninn"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-iansui": ['"Iansui"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-lxgw-wenkai-mono-tc": ['"LXGW WenKai Mono TC"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-lxgw-wenkai-tc": ['"LXGW WenKai TC"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-wdxl-lubrifont-tc": ['"WDXL Lubrifont TC"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-chiron-goround-tc": ['"Chiron GoRound TC"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-chiron-hei-hk": ['"Chiron Hei HK"', "var(--font-sans)", "var(--font-emoji)"],
			"chinese-chiron-sung-hk": ['"Chiron Sung HK"', "var(--font-serif)", "var(--font-emoji)"],
		},
		colors: {
			transparent: "transparent",
			current: "currentColor",
			primary: "rgb(var(--primary) / <alpha-value>)",
			"primary-content": "rgb(var(--primary-content) / <alpha-value>)",
			"primary-content-200": "rgb(var(--primary-content-200) / <alpha-value>)",
			"primary-content-300": "rgb(var(--primary-content-300) / <alpha-value>)",
			"primary-content-400": "rgb(var(--primary-content-400) / <alpha-value>)",
			"primary-content-500": "rgb(var(--primary-content-500) / <alpha-value>)",
			secondary: "rgb(var(--secondary) / <alpha-value>)",
			"secondary-content": "rgb(var(--secondary-content) / <alpha-value>)",
			accent: "rgb(var(--accent) / <alpha-value>)",
			"accent-content": "rgb(var(--accent-content) / <alpha-value>)",
			neutral: "rgb(var(--neutral) / <alpha-value>)",
			"neutral-content": "rgb(var(--neutral-content) / <alpha-value>)",
			"base-100": "rgb(var(--base-100) / <alpha-value>)",
			"base-200": "rgb(var(--base-200) / <alpha-value>)",
			"base-300": "rgb(var(--base-300) / <alpha-value>)",
			"base-400": "rgb(var(--base-400) / <alpha-value>)",
			"base-500": "rgb(var(--base-500) / <alpha-value>)",
			"base-content": "rgb(var(--base-content) / <alpha-value>)",
			"base-content-200": "rgb(var(--base-content-200) / <alpha-value>)",
			"base-content-300": "rgb(var(--base-content-300) / <alpha-value>)",
			"base-content-400": "rgb(var(--base-content-400) / <alpha-value>)",
		},
	},
	plugins: [],
} satisfies Config;
